export default colors = {
    backgroundColorLogin : "#F5F5F5",
    backgroundColorMainMenu : "#d7eaea",
    backgroundColor : "#F5F5F5",
    primaryRed : "",
    secondaryRed : "",
    primaryOpacity : "#00A6A6",
    secondaryOpacity : "",
    primariBotton : "#285055",
    secondaryBotton : "#377979",
    success : "",
    error : "",
    help : "",
    primaryFont : "white",
    black : "#615F66",
};